########################################################################################
# Create an image suitable to act as the base image for all fish services
########################################################################################
FROM node:14-alpine

RUN apk update && apk upgrade && apk add bash curl && rm -rf /var/cache/apk/*

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

# Install pm2
RUN npm install pm2 -g

USER node
