version: '3.7'
services:
  #######################################################
  # Localstack services for development
  #
  # - DynamoDB (http port 4569)
  # - S3 (http port 4572)...
  # - SQS (http port 4576)
  # - CloudFormation (http port 4581)
  #######################################################
  localstack:
    image: localstack/localstack:1.2.0
    ports:
      - '4563-4599:4563-4599'
      - '${PORT_WEB_UI-4080}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=s3,dynamodb,secretsmanager,cloudformation
      - DEFAULT_REGION=eu-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DYNAMODB_HEAP_SIZE=1G
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/localstack:/var/lib/localstack
      - ./resources/infrastructure/localstack/localstack-init.sh:/docker-entrypoint-initaws.d/init.sh
      - ./resources/infrastructure/localstack/localstack-cfn.yml:/docker-entrypoint-initaws.d/localstack-cfn.yml
    deploy:
      restart_policy:
        condition: on-failure

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8002:8001'
    environment:
      - DYNAMO_ENDPOINT=http://host.docker.internal:4566
    deploy:
      restart_policy:
        condition: on-failure

  #######################################################
  # Redis
  #######################################################
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data
    deploy:
      restart_policy:
        condition: on-failure

  redis_insight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    volumes:
      - ./volumes/redisinsight:/db
    deploy:
      restart_policy:
        condition: on-failure

  redis_commander:
    image: rediscommander/redis-commander
    ports:
      - '8003:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379
    deploy:
      restart_policy:
        condition: on-failure

  #######################################################
  # Elasticmq (SQS provider)
  #######################################################
  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - '9324:9324'
    volumes:
      - type: bind
        read_only: true
        source: resources/infrastructure/elasticmq/elasticmq.conf
        target: /opt/elasticmq.conf
    deploy:
      restart_policy:
        condition: on-failure

  #######################################################
  # nginx
  #######################################################
  nginx:
    image: nginx:alpine
    environment:
      - WEBSALES_LISTEN=3043
      - TELESALES_LISTEN=3143
      - WEBSALES_UPSTREAM_PORT=3000
      - TELESALES_UPSTREAM_PORT=3100
    volumes:
      - ./resources/infrastructure/nginx/templates:/etc/nginx/templates
      - ./resources/infrastructure/nginx/ssl:/etc/nginx/ssl
    ports:
      - '3043:3043'
      - '3143:3143'
    deploy:
      restart_policy:
        condition: on-failure
