version: '3.8'
services:
  ##############################################################################################################
  # rod_licensing gafl_webapp
  ##############################################################################################################
  gafl_webapp:
    image: rod_licensing/gafl_webapp:${TAG:-latest}
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    env_file:
      - ./env/.gafl_webapp.env
      - ./env/.gafl_webapp.secrets.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # rod-licensing gafl_webapp_telesales
  ##############################################################################################################
  gafl_webapp_telesales:
    image: rod_licensing/gafl_webapp:${TAG:-latest}
    volumes:
      - ../:/app
    ports:
      - 3100:3100
    env_file:
      - ./env/.gafl_webapp_telesales.env
      - ./env/.gafl_webapp_telesales.secrets.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # rod_licensing payment_mop_up_job
  ##############################################################################################################
  payment_mop_up_job:
    image: rod_licensing/payment_mop_up_job:${TAG:-latest}
    volumes:
      - ../:/app
    env_file:
      - ./env/.payment_mop_up_job.env
      - ./env/.payment_mop_up_job.secrets.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5m

  ##############################################################################################################
  # rod_licensing sales_api
  ##############################################################################################################
  sales_api:
    image: rod_licensing/sales_api:${TAG:-latest}
    volumes:
      - ../:/app
    ports:
      - 4000:4000
    env_file:
      - ./env/.sales_api.env
      - ./env/.sales_api.secrets.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # rod_licensing pocl_job
  ##############################################################################################################
  pocl_job:
    image: rod_licensing/pocl_job:${TAG:-latest}
    volumes:
      - ../:/app
      - ./resources/infrastructure/sftp/ssh_host_rsa_key:/etc/pocl/keys
    env_file:
      - ./env/.pocl_job.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5m

  ##############################################################################################################
  # rod_licensing fulfilment_job
  ##############################################################################################################
  fulfilment_job:
    image: rod_licensing/fulfilment_job:${TAG:-latest}
    volumes:
      - ../:/app
      - ./resources/infrastructure/sftp/ssh_host_rsa_key:/etc/fulfilment/keys
    env_file:
      - ./env/.fulfilment_job.env
      - ./env/.fulfilment_job.secrets.env
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: any
        delay: 24h

  ##############################################################################################################
  # rod_licensing sqs_receiver
  ##############################################################################################################
  sqs_receiver:
    image: rod_licensing/sqs_receiver:${TAG:-latest}
    volumes:
      - ../:/app
    env_file:
      - ./env/.sqs_receiver.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # rod_licensing recurring_payments_job
  ##############################################################################################################
  recurring_payments_job:
    image: rod_licensing/recurring_payments_job:${TAG:-latest}
    volumes:
      - ../:/app
    env_file:
      - ./env/.recurring_payments_job.env
      - ./env/.recurring_payments_job.secrets.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

#######################################################
# Network configuration
#######################################################
networks:
  internal:
    driver: overlay
