export * from './entities/contact.entity.js'
export * from './entities/permission.entity.js'
export * from './entities/permit.entity.js'
export * from './entities/transaction-currency.entity.js'
export * from './entities/concession.entity.js'
export * from './entities/permit-concession.entity.js'
export { dynamicsWebApi } from './client/dynamics-client.js'
export * from './client/entity-manager.js'
