export default {
  RECEIVER_PREFIX: 'TEST',
  TEST_URL: 'http://0.0.0.0:9325/queue/SalesQueue.fifo',
  TEST_MAX_POLLING_INTERVAL_MS: 1,
  TEST_ATTEMPTS_WITH_NO_DELAY: 2,
  TEST_VISIBILITY_TIMEOUT_MS: 1,
  TEST_WAIT_TIME_MS: 2,
  TEST_SUBSCRIBER: 'http://localhost:4000',
  TEST_SUBSCRIBER_TIMEOUT_MS: 5
}
